import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footers/Footers";
import ToastProvider from "@/components/ToastProvider/ToastProvider";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${hindSiliguri.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#f0f6f1]">
          <ToastProvider/>
          <Navbar/>
        <main className="w-full max-w-7xl mx-auto">
        {children}
        </main>
          <Footer/>
        </body>
    </html>
  );
}
